"use client"

import Navbar from '@/components/sections/Navbar'
import { useState , useEffect } from "react"
import './globals.css'
import SocialMedia from '@/components/others/SocialMedia'
import FixedPageLocation from '@/components/others/FixedPageLocation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setTimeout(() => {
      setLoading(false)
    },1000)
  }, [])
  
  return (
    <html lang="en">
      <body
      className='
      xl:px-[128px]
      md:px-[98px]
      sm:px-[32px]
      px-[16px]
      '>
        {
          loading ?
          <div>
            loading...
          </div>
          :
          <>
          <SocialMedia/>
          <Navbar/>
          {children}
          </>
        }
      </body>
    </html>
  )
}
